---
name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT: true
          YAMLLINT: true
